### ISSUE TITLE
Errors on purge again.

### ISSUE THREAD

**Issue by ScuroK** [megoesrawr/LWCEntityLocking#35] opened 2017-09-10 11:17 UTC
I get tons of error on /lwc admin purge
First i thought it was fixed but then the errors returned.

#34

**Comment by sigmaroot** [comment] 2017-09-12 10:52
Confirmed. There is a new 1.8.9 build.
I'm gonna try it in a few minutes.

Seems that this error occurs if you perform a second pruge command since restart.

I'm gonna report the results of the new 1.8.9 dev build. here.

**Comment by sigmaroot** [comment] 2017-09-12 11:35
Seems to be successfully fixed in 1.8.9 😄

**Closed** 2017-09-12 16:28 UTC
